<a href="https://colab.research.google.com/github/akhila-attem/UNP-Assignments/blob/main/Revision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import style

import seaborn as sns

In [3]:
data=pd.read_csv("Housing.csv",index_col=0)
data

,LandUse,PropertyAddress,SaleDate,SalePrice,Acre,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
UniqueID,,,,,,,,,,,,
2045,SINGLE FAMILY,"1808 FOX CHASE DR, GOODLETTSVILLE","April 9, 2013",240000,2.3,50000.0,168200.0,235700.0,1986.0,3.0,3.0,0.0
16918,SINGLE FAMILY,"1832 FOX CHASE DR, GOODLETTSVILLE","June 10, 2014",366000,3.5,50000.0,264100.0,319000.0,1998.0,3.0,3.0,2.0
54582,SINGLE FAMILY,"1864 FOX CHASE DR, GOODLETTSVILLE","September 26, 2016",435000,2.9,50000.0,216200.0,298000.0,1987.0,4.0,3.0,0.0
43070,SINGLE FAMILY,"1853 FOX CHASE DR, GOODLETTSVILLE","January 29, 2016",255000,2.6,50000.0,147300.0,197300.0,1985.0,3.0,3.0,0.0
22714,SINGLE FAMILY,"1829 FOX CHASE DR, GOODLETTSVILLE","October 10, 2014",278000,2.0,50000.0,152300.0,202300.0,1984.0,4.0,3.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
30469,SINGLE FAMILY,"1435 WINDING CREEK DR, NOLENSVILLE","May 27, 2015",157500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27707,SINGLE FAMILY,"1423 WINDING CREEK DR, NOLENSVILLE","March 2, 2015",145000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52709,VACANT RESIDENTIAL LAND,"1804 GRACE POINT LN, NOLENSVILLE","August 16, 2016",234611,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54042,VACANT RESIDENTIAL LAND,"1709 PARK TERRACE LN, NOLENSVILLE","September 7, 2016",93844,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54043,VACANT RESIDENTIAL LAND,"1713 PARK TERRACE LN, NOLENSVILLE","September 7, 2016",93844,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN